---
parser: babel-eslint
extends:
- airbnb
env:
  browser: true
  node: true
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    experimentalObjectRestSpread: true
rules:
  no-console: 'off'
  comma-dangle: 'off'
  react/jsx-filename-extension: 'off'
  react/prop-types: 'off'
  jsx-a11y/label-has-for:
  - 2
  - required:
      every:
      - id
  jsx-a11y/label-has-associated-control: 0
settings:
  import/resolver:
    webpack:
      config: webpack.config.js
globals:
  NProgress: true
